parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     caesar
    database_user:     root
    database_password: ~

    mailer_transport:    gmail
    mailer_host:         smtp.gmail.com
    mailer_user:         strategesim@gmail.com
    mailer_password:     cemen123
    mailer_auth_mode:    ~
    mailer_encryption:   ssl
    mailer_port:         465

    locale:            fr
    secret:            ThisTokenIsNotSoSecretChangeIt
