caesar_web_mining:
    resource: "@CaesarWebMiningBundle/Resources/config/routing.yml"

caesar_location:
    resource: "@CaesarLocationBundle/Resources/config/routing.yml"

caesar_tag:
    resource: "@CaesarTagBundle/Resources/config/routing.yml"

caesar_resource:
    resource: "@CaesarResourceBundle/Resources/config/routing.yml"

caesar_admin:
    resource: "@CaesarAdminBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/admin
    requirements: 
        _locale: fr|en
    defaults: {_locale: 'fr'}
    
caesar_client:
    resource: "@CaesarUserBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements: 
        _locale: fr|en
    defaults: {_locale: 'fr'}

caesar_client_default:
    pattern:  /
    defaults: { _controller: CaesarUserBundle:User:index, _locale: 'fr'}