jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Caesar\UserBundle\Entity\User:
            algorithm:        sha512
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_USER:  ROLE_USER
        ROLE_USER_IDENTIFIED: ROLE_USER_IDENTIFIED
        ROLE_USER_AUTHENTIFIED: [ROLE_USER_AUTHENTIFIED, ROLE_USER_IDENTIFIED]
        ROLE_ADMIN: ROLE_ADMIN
    providers:
        main:
            entity: { class: Caesar\UserBundle\Entity\User, property: username }
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            anonymous: ~
        caesar_admin:
            pattern:   /admin
            anonymous: ~
            logout:
                path:   caesar_admin_logout
                target: caesar_admin_login
            form_login:
                login_path:  caesar_admin_login
                check_path:  caesar_admin_login_check
                success_handler: caesar_user_security.component.authentication.handler.login_handler
                failure_handler: caesar_user_security.component.authentication.handler.login_handler
                failure_path:   null
            http_basic: true
        caesar:
            pattern:   ^/
            anonymous: ~
            logout:
                path:   caesar_client_logout
                target: caesar_client_homepage
            form_login:
                login_path:  caesar_client_login
                check_path:  caesar_client_login_check
                success_handler: caesar_user_security.component.authentication.handler.login_handler
                failure_handler: caesar_user_security.component.authentication.handler.login_handler
                failure_path:   null
            http_basic: true
    access_control:
        - { path: login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: profile, roles: ROLE_USER_IDENTIFIED}
        - { path: admin, roles: ROLE_ADMIN }
