jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Caesar\UserBundle\Entity\User:
            algorithm:        sha512
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        caesar:
            id: caesar_user_provider
        main:
            entity: { class: Caesar\UserBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        caesar:
            pattern:  ^/
            anonymous: ~
            logout:
                path:   caesar_logout
                target: caesar_client_homepage
            form_login:
                login_path:  caesar_client_login
                check_path:  caesar_client_login_check
                success_handler: caesar_user_security.component.authentication.handler.login_handler
                failure_handler: caesar_user_security.component.authentication.handler.login_handler
                failure_path:   null
            http_basic: true

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #
        # You must uncomment the two following rules to restrict access to paths
        # starting with the /_internal prefix to only localhost
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        #- { path: ^/_internal/secure, roles: ROLE_NO_ACCESS }
