<?php

namespace Caesar\TagBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository {

    public function getTagFromToSortBy($page, $sort, $direction) {
        $nb_per_page = 10;
        $min = ($page - 1) * $nb_per_page;
        $qb = $this->createQueryBuilder('t');
        $qb->orderBy('t.' . $sort, $direction)
                ->setFirstResult($min)
                ->setMaxResults($nb_per_page);
        return $qb->getQuery()->getResult();
    }

    public function count() {
        $qb = $this->createQueryBuilder('t');
        $qb->select('count(t.id)');
        return $qb->getQuery()->getSingleScalarResult();
    }

    public function findAllInArray() {
        $qb = $this->createQueryBuilder('u');
        $qb->select();
        return $qb->getQuery()->getArrayResult();
    }

}
