caesar_admin_homepage:
    pattern:  /
    defaults: { _controller: CaesarAdminBundle:Admin:index}

caesar_admin_resource_homepage:
    pattern:  /resource/{page}/{sort}/{direction}
    defaults: { _controller: CaesarAdminBundle:Resource:index, page:1, sort:'code', direction:'asc'}
    requirements:
        page:  \d+
        direction: asc|desc

caesar_admin_resource_description:
    pattern:  /resource/description/{id}
    defaults: { _controller: CaesarAdminBundle:Resource:description, id = 1}
    requirements:
        id:  \d+

caesar_admin_borrowing_homepage:
    pattern:  /borrowing/{page}/{sort}/{direction}
    defaults: { _controller: CaesarAdminBundle:Borrowing:index, page:1, sort:'id', direction:'asc'}
    requirements:
        page:  \d+
        direction: asc|desc

caesar_admin_resource_add:
    pattern:  /resource/add
    defaults: { _controller: CaesarAdminBundle:Resource:add }

caesar_admin_resource_update:
    pattern:  /resource/update/{id}
    defaults: { _controller: CaesarAdminBundle:Resource:update }
    requirements:
        id:  \d+

caesar_admin_resource_delete:
    pattern:  /resource/delete/{id}
    defaults: { _controller: CaesarAdminBundle:Resource:delete }
    requirements:
        id:  \d+

caesar_admin_resource_skeleton:
    pattern:  /resource/skeleton
    defaults: { _controller: CaesarAdminBundle:Resource:skeleton }

caesar_admin_user_update:
    pattern:  /user/update/{id}
    defaults: { _controller: CaesarAdminBundle:User:update}
    requirements:
        id:  \d+

caesar_admin_user_delete:
    pattern:  /user/delete/{id}
    defaults: { _controller: CaesarAdminBundle:User:delete }
    requirements:
        id:  \d+

caesar_admin_user_homepage:
    pattern:  /user/{page}/{sort}/{direction}
    defaults: { _controller: CaesarAdminBundle:User:index, page:1, sort:'codeBu', direction:'asc'}
    requirements:
        page:  \d+
        direction: asc|desc

caesar_admin_user_add:
    pattern:  /user/add
    defaults: { _controller: CaesarAdminBundle:User:add }

caesar_admin_shelf_homepage:
    pattern:  /shelf/{page}/{sort}/{direction}
    defaults: { _controller: CaesarAdminBundle:Shelf:index, page:1, sort:'id', direction:'asc'}
    requirements:
        page:  \d+
        direction: asc|desc

caesar_admin_shelf_add:
    pattern:  /shelf/add
    defaults: { _controller: CaesarAdminBundle:Shelf:add }

caesar_admin_shelf_update:
    pattern:  /shelf/update/{id}
    defaults: { _controller: CaesarAdminBundle:Shelf:update }
    requirements:
        id:  \d+

caesar_admin_shelf_delete:
    pattern:  /shelf/delete/{id}
    defaults: { _controller: CaesarAdminBundle:Shelf:delete}
    requirements:
        id:  \d+

caesar_admin_tag_homepage:
    pattern:  /tag/{page}/{sort}/{direction}
    defaults: { _controller: CaesarAdminBundle:Tag:index, page:1, sort:'code', direction:'asc'}
    requirements:
        page:  \d+
        direction: asc|desc

caesar_admin_tag_generate:
    pattern:  /tag/generate
    defaults: { _controller: CaesarAdminBundle:Tag:generate}

caesar_admin_tag_delete:
    pattern:  /tag/delete/{id}
    defaults: { _controller: CaesarAdminBundle:Tag:delete }
    requirements:
        id:  \d+

caesar_admin_tag_barcode:
    pattern:  /tag/barcode/{text}
    defaults: { _controller: CaesarAdminBundle:Tag:barcode }

caesar_admin_format_add:
    pattern:  /tag/format/add
    defaults: { _controller: CaesarAdminBundle:Tag:formatAdd}

caesar_admin_format_json:
    pattern:  /tag/format/{id}
    defaults: { _controller: CaesarAdminBundle:Tag:formatAjax, id = 1}
    requirements:
        id:  \d+