parameters:
#    caesar_resource.example.class: Caesar\ResourceBundle\Example

services:
#    caesar_resource.example:
#        class: %caesar_resource.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
