parameters:
#    caesar_admin.example.class: Caesar\AdminBundle\Example

services:
#    caesar_admin.example:
#        class: %caesar_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
