parameters:
#    caesar_location.example.class: Caesar\LocationBundle\Example

services:
#    caesar_location.example:
#        class: %caesar_location.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
