<?php

namespace Caesar\AdminBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class TagController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Caesar\AdminBundle\Controller\TagController();
        return $instance;
    }
}
