<?php

namespace Caesar\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BorrowingArchiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BorrowingArchiveRepository extends EntityRepository
{
     public function getArchivedBorrowingsFromToSortBy($page, $sort, $direction, $user, $resource) {
        $nb_per_page = 10;
        $min = ($page - 1) * $nb_per_page;
        $qb = $this->createQueryBuilder('b');
        if ($user != null) {
            $qb->where('b.user.id = ' . $user->getId());
            if ($resource != null) {
                $qb->andWhere('b.resource.id = ' . $resource->getId());
            }
        }
        
        if ($resource != null) {
            $qb->where('b.resource.id = ' . $resource->getId());
        }
        $qb->orderBy('b.' . $sort, $direction)
                ->setFirstResult($min)
                ->setMaxResults($nb_per_page);
        return $qb->getQuery()->getResult();
    }
    
}
