caesar_client_homepage:
    pattern:  /
    defaults: { _controller: "CaesarUserBundle:User:home" }

caesar_client_search:
    pattern:  /search/{page}/{sort}/{direction}
    defaults: { _controller: "CaesarUserBundle:User:search", page:1, sort:'code', direction:'asc'}
    requirements:
        page:  \d+
        direction: asc|desc

caesar_client_logout:
     pattern: /logout

caesar_client_login:
    pattern:  /login
    defaults: { _controller: "CaesarUserBundle:User:login" }

caesar_client_login_check:
    pattern: /login_check

caesar_client_register:
    pattern:  /register
    defaults: { _controller: "CaesarUserBundle:User:register" }

caesar_client_profile:
    pattern:  /profile
    defaults: { _controller: "CaesarUserBundle:User:profile" }
    
caesar_client_modify_user:
    pattern: /profile/modify
    defaults: { _controller: "CaesarUserBundle:User:modifyProfile" }
    
caesar_client_authenticate:
    pattern: /authenticate
    defaults: { _controller: "CaesarUserBundle:User:authenticate" }
    
caesar_client_resetting:
    pattern:  /resetting
    defaults: { _controller: "CaesarUserBundle:User:resetting" }

caesar_client_borrowing:
    pattern:  /borrowing
    defaults: { _controller: "CaesarUserBundle:User:borrowing", page:1, sort:'id', direction:'asc'}
    requirements:
        page:  \d+
        direction: asc|desc

caesar_client_reservation:
    pattern:  /reservation
    defaults: { _controller: "CaesarUserBundle:User:reservation", page:1, sort:'id', direction:'asc'}
    requirements:
        page:  \d+
        direction: asc|desc