parameters:
#    caesar_client.example.class: Caesar\ClientBundle\Example

services:
#    caesar_client.example:
#        class: %caesar_client.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
