parameters:
    caesar_user_provider.class: Caesar\UserBundle\Entity\UserRepository
    caesar_user_security.component.authentication.handler.login_handler.class: Caesar\UserBundle\Security\Authentication\Handler\LoginHandler
services:
    user_metadata:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments: ['Caesar\UserBundle\Entity\User']
    caesar_user_provider:
        class: "%caesar_user_provider.class%"
        arguments: ["@doctrine.orm.entity_manager", "@user_metadata"]
    caesar.security.authentication.provider:
        class:  Caesar\UserBundle\Security\Authentication\Provider\CaesarUserAuthentificationProvider
        arguments: ['@caesar_user_provider', "@security.user_checker", "@security.encoder_factory"]
    caesar.security.authentication.listener:
        class: Caesar\UserBundle\Security\Firewall\CaesarUserListener
        arguments: ["@security.context", "@caesar.security.authentication.provider",  "@security.authentication.session_strategy", "@security.http_utils","@kernel"]
    caesar_user_security.component.authentication.handler.login_handler:
        class:  %caesar_user_security.component.authentication.handler.login_handler.class%
        arguments:  ["@router", "@security.context"]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
