parameters:
#    caesar_tag.example.class: Caesar\TagBundle\Example

services:
#    caesar_tag.example:
#        class: %caesar_tag.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
