parameters:
#    caesar_shelf.example.class: Caesar\shelfBundle\Example

services:
#    caesar_shelf.example:
#        class: %caesar_shelf.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
